### ISSUE TITLE
yolov8x-seg.onnx can not work

### ISSUE THREAD

**Issue by hktalent** [Hyuto/yolov8-seg-onnxruntime-web#2]
yolov8x-seg.onnx can not work
<img width="696" alt="image" src="https://github.com/Hyuto/yolov8-seg-onnxruntime-web/assets/18223385/a4af90e9-41f0-4f2f-8053-125bca80013d">
<img width="629" alt="image" src="https://github.com/Hyuto/yolov8-seg-onnxruntime-web/assets/18223385/3f9c0685-88c1-4301-8a07-0b2694b00fd4">

**Comment by Hyuto** [comment]
Hello, I've test in on my local machine and it works without any error occur.

![image](https://github.com/Hyuto/yolov8-seg-onnxruntime-web/assets/64422277/6f758ab8-e24d-45f8-8926-be9d5d230386)

**Comment by hktalent** [comment]
ok, thanks
